services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml

  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - qdrant
    ports:
      - "8000:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - GOOGLE_API_KEY=<Replace with your Google API Key>
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

configs:
  qdrant_config:
    content: |
      log_level: INFO
